### ISSUE TITLE
Edge and mini-edge agents downloads

### ISSUE THREAD

**Issue by 4refr0nt** [mainflux/gateways#2]
Where I can download Edge and mini-edge agents?
Where is doc for Edgeflux?
Edgeflux is hardware agnostic and it can be used with any gateway. Where I can find crosscompile instructions for Edgeflux agents?

Thanks!

**Comment by drasko** [comment]
Edgeflux is a codename, we should yet decide how will be called really :). Most probably Edge Agent.

It is not yet opensourced, but this should happen in a week or two. It is a small Go app, completely portable to any IoT gateway.

@4refr0nt I can see you are playing with Mainflux, and would be interested to understand what are you building and what are the requirements. If you can share this with us, ping us at info@mainflux.com.
